name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello! Thank you for letting me know about your issue. I will hopefully reply to you soon to help resolve your issue. If you are reporting a bug, make sure you have included the debug information, found in Settings => Debug Info (On version 1.10.0 and newer).'
        pr-message: 'Hello! Thank you for your contribution to the project. I will hopefully check out your pull request soon and will either merge it or let you know of any issues I find. :)'
